version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_USER=sa
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    networks:
      - HRISNetwork
  backend:
    build:
      context: ./backend
      dockerfile: HRIS/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    ports:
      - "8000:80"
    networks:
      - HRISNetwork
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - HRISNetwork
networks:
  HRISNetwork:
    driver: bridge